"""empty message

Revision ID: 995094591e86
Revises: 217ca8398bf0
Create Date: 2021-07-06 21:17:52.686086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995094591e86'
down_revision = '217ca8398bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order__item', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order__item', 'quantity')
    # ### end Alembic commands ###
